final_exam/addressbook/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

from . import views
from .views import RegisterView, ContactListView, ContactCreate, ContactImport, ContactExport, ContactUpdate, ContactDelete

urlpatterns = [
    url(r'^$', auth_views.LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^home/$', ContactListView.as_view(), name='index'),
    url(r'^contact/', include([
        url(r'^add/$', ContactCreate.as_view(), name='add_contact'),
        url(r'^import/$', ContactImport.as_view(), name='import_contact'),
        url(r'^export/$', ContactExport.as_view(), name='export_contact'),
    ])),
    url(r'^contact/(?P<contact_id>[0-9]+)/', include([
        url(r'^update/$', ContactUpdate.as_view(), name='edit_contact'),
        url(r'^delete/$', ContactDelete.as_view(), name='delete_contact')
    ]))
]

final_exam/final_exam/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('addressbook.urls'))
]

final_exam/addressbook/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Contact(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    contact_number = models.CharField(max_length=13)
    address = models.TextField()

final_exam/addressbook/forms.py
import io, csv

from django import forms

from .models import Contact

class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = ('first_name', 'last_name', 'contact_number', 'address')

class DataForm(forms.Form):
    file_contacts = forms.FileField()

final_exam/addressbook/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import csv, logging, io

from django.utils.encoding import smart_str
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm

from django.utils.decorators import method_decorator

from django.views import View
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import FormView, CreateView, DeleteView, UpdateView
from django.views.generic.list import MultipleObjectMixin

from .models import Contact
from .forms import ContactForm, DataForm

# Create your views here.
class RegisterView(View):
    template_name = 'registration/register.html'
    form_class = UserCreationForm

    def get(self, request, *args, **kwargs):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
        else:
            return render(request, self.template_name, {'form': form})


@method_decorator(login_required, name='dispatch')
class ContactListView(ListView):
    model = Contact
    context_object_name = 'contact_list'
    template_name = 'addressbook/home.html'
    paginate_by = 10

    def get_queryset(self):
        return Contact.objects.filter(user=self.request.user)

@method_decorator(login_required, name='dispatch')
class ContactCreate(CreateView):
    model = Contact
    fields = ['first_name', 'last_name', 'contact_number', 'address']
    success_url = '/home/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ContactCreate, self).form_valid(form)

@method_decorator(login_required, name='dispatch')
class ContactUpdate(UpdateView):
    model = Contact
    fields = ['first_name', 'last_name', 'contact_number', 'address']
    pk_url_kwarg = 'contact_id'
    success_url = '/home/'

@method_decorator(login_required, name='dispatch')
class ContactDelete(DeleteView):
    model = Contact
    pk_url_kwarg = 'contact_id'
    success_url = '/home/'

@method_decorator(login_required, name='dispatch')
class ContactImport(View):
    template_name = 'addressbook/contact_import.html'
    form_class = DataForm

    def get(self, request, *args, **kwargs):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = DataForm(request.POST, request.FILES)

        csv_file = request.FILES['file_contacts']

        if not csv_file.name.endswith('.csv'):
            messages.error(request,'File is not CSV type')
            return HttpResponseRedirect(reverse('import_contact'))
        
        if csv_file.multiple_chunks():
            messages.error(request,"Uploaded file is too big (%.2f MB)." % (csv_file.size/(1000*1000),))
            return HttpResponseRedirect(reverse('import_contact'))

        if form.is_valid():
            f = io.TextIOWrapper(form.cleaned_data['file_contacts'].file)
            reader = csv.DictReader(f)
               
            for contact in reader:
                obj_value = Contact.objects.filter(user=request.user, first_name=contact['FirstName'], last_name=contact['LastName'], contact_number=contact['ContactNo'], address=contact['Address'])

                if not obj_value:
                    if len(contact['ContactNo']) > 13:
                        messages.error(request,"Invalid contact number for %s %s" % (contact['FirstName'], contact['LastName']))
                        return HttpResponseRedirect(reverse('import_contact'))
                    else:
                        Contact.objects.create(user=request.user, first_name=contact['FirstName'], last_name=contact['LastName'], contact_number=contact['ContactNo'], address=contact['Address'])
            
            return redirect('index')
 
@method_decorator(login_required, name='dispatch')
class ContactExport(View):

    def get(self, request, *args, **kwargs):
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename=address-book.csv'
        writer = csv.writer(response, csv.excel)
        writer.writerow([
            smart_str(u"FirstName"),
            smart_str(u"LastName"),
            smart_str(u"ContactNo"),
            smart_str(u"Address"),
        ])
        contacts = Contact.objects.filter(user=request.user)
        for data in contacts:
            writer.writerow([
                smart_str(data.first_name),
                smart_str(data.last_name),
                smart_str(data.contact_number),
                smart_str(data.address),
            ])
        return response


# Function-based Views
# def register(request):
#     if request.method == "POST":
#         form = UserCreationForm(request.POST)
#         if form.is_valid():
#             form.save()
#             username = form.cleaned_data.get('username')
#             raw_password = form.cleaned_data.get('password1')
#             user = authenticate(username=username, password=raw_password)
#             login(request, user)
#             return redirect('index')
#     else: 
#         form = UserCreationForm()
#     return render(request, 'registration/register.html', {'form': form})

# @login_required(login_url='/')
# def index(request):
#     contact_list = Contact.objects.filter(user=request.user)

#     paginator = Paginator(contact_list, 10)

#     page = request.GET.get('page')

#     try:
#         contact = paginator.page(page)
#     except PageNotAnInteger:
#         contact = paginator.page(1)
#     except EmptyPage:
#         contact = paginator.page(paginator.num_pages)

#     return render(request, 'addressbook/home.html', {'contact': contact})

# @login_required(login_url='/')
# def add_contact(request):
#     if request.method == "POST":
#         form = ContactForm(request.POST)
#         if form.is_valid():
#             contact = form.save(commit=False)
#             contact.user = request.user
#             contact.save()
#             return redirect('index')
#     else:
#         form = ContactForm()
#     return render(request, 'addressbook/contact_detail.html', {'form': form})

# @login_required(login_url='/')
# def edit_contact(request, contact_id):
#     contact = Contact.objects.get(pk=contact_id)
#     if request.method == "POST":
#         form = ContactForm(request.POST, instance=contact)
#         if form.is_valid():
#             contact = form.save(commit=False)
#             contact.user = request.user
#             contact.save()
#             return redirect('index')
#     else:
#         form = ContactForm(instance=contact)
#     return render(request, 'addressbook/contact_detail.html', {'form': form})

# @login_required(login_url='/')
# def delete_contact(request, contact_id):
#     contact = Contact.objects.get(pk=contact_id)
#     if request.method == "POST":
#         contact.delete()
#         return redirect('index')
#     else:
#         return render(request, 'addressbook/contact_confirm.html', {'contact': contact})

# @login_required(login_url='/')
# def import_contact(request):
#     if request.method == "POST":
#         form = DataForm(request.POST, request.FILES)

#         csv_file = request.FILES['file_contacts']

#         if not csv_file.name.endswith('.csv'):
# 			messages.error(request,'File is not CSV type')
# 			return HttpResponseRedirect(reverse('import_contact'))
        
#         if csv_file.multiple_chunks():
# 			messages.error(request,"Uploaded file is too big (%.2f MB)." % (csv_file.size/(1000*1000),))
# 			return HttpResponseRedirect(reverse('import_contact'))

#         if form.is_valid():
#             f = io.TextIOWrapper(form.cleaned_data['file_contacts'].file)
#             reader = csv.DictReader(f)
               
#             for contact in reader:
#                 obj_value = Contact.objects.filter(user=request.user, first_name=contact['FirstName'], last_name=contact['LastName'], contact_number=contact['ContactNo'], address=contact['Address'])

#                 if not obj_value:
#                     if len(contact['ContactNo']) > 13:
#                         messages.error(request,"Invalid contact number for %s %s" % (contact['FirstName'], contact['LastName']))
#                         return HttpResponseRedirect(reverse('import_contact'))
#                     else:
#                         Contact.objects.create(user=request.user, first_name=contact['FirstName'], last_name=contact['LastName'], contact_number=contact['ContactNo'], address=contact['Address'])
            
#             return redirect('index')
        
#     else:
#         form = DataForm()
#         return render(request, 'addressbook/contact_import.html', {'form': form})

# @login_required(login_url='/')
# def export_contact(request):
#     response = HttpResponse(content_type='text/csv')
#     response['Content-Disposition'] = 'attachment; filename=address-book.csv'
#     writer = csv.writer(response, csv.excel)
#     writer.writerow([
#         smart_str(u"FirstName"),
#         smart_str(u"LastName"),
#         smart_str(u"ContactNo"),
#         smart_str(u"Address"),
#     ])
#     contacts = Contact.objects.filter(user=request.user)
#     for data in contacts:

final_exam/addressbook/templates/addressbook/contact_confirm.html
{% extends 'layouts/base.html' %} 
{% load static %} 

{% block content %}
<div class="container-login100">
    <div class="wrap-login100">
        <div class="login100-form-title" style="background-image: url({% static 'images/header.jpg' %});">
            <span class="login100-form-title-1">
                Delete Contact
            </span>
            <div class="row">
                <div class="col-md-12">
                    <a href="{% url 'index' %}" class="btn btn-info">Back <i class="fa fa-arrow-left"></i></a>
                </div>
            </div>
        </div>
        

        <form class="login100-form validate-form" method="POST">
            {% csrf_token %}

            <div class="row">
                <div class="col-md-12 text-center">
                    <p>Are you sure you want to delete this contact?</p>
                    <h6>{{ contact.first_name }} {{ contact.last_name }}</h6>
                </div>
            </div>
            
            <div class="row mt-3">
                <div class="col-md-12">
                    <div class="container-login100-form-btn">
                        <button class="login100-form-btn mr-3" type="submit">
                            Yes
                        </button>
                        <a href="{% url 'index' %}" class="login100-form-btn" style="background-color: #F34434">
                            No
                        </a>
                    </div>
                </div>
            </div>
            
        </form>
    </div>
</div>
{% endblock %}

final_exam/addressbook/templates/addressbook/contact_confirm_delete.html
{% extends 'layouts/base.html' %} 
{% load static %} 

{% block content %}
<div class="container-login100">
    <div class="wrap-login100">
        <div class="login100-form-title" style="background-image: url({% static 'images/header.jpg' %});">
            <span class="login100-form-title-1">
                Delete Contact
            </span>
            <div class="row">
                <div class="col-md-12">
                    <a href="{% url 'index' %}" class="btn btn-info">Back <i class="fa fa-arrow-left"></i></a>
                </div>
            </div>
        </div>
        
        <form class="login100-form validate-form" method="POST">
            {% csrf_token %}

            <div class="row">
                <div class="col-md-12 text-center">
                    <p>Are you sure you want to delete this contact?</p>
                </div>
            </div>
            
            <div class="row mt-3">
                <div class="col-md-12">
                    <div class="container-login100-form-btn">
                        <button class="login100-form-btn mr-3" type="submit">
                            Yes
                        </button>
                        <a href="{% url 'index' %}" class="login100-form-btn" style="background-color: #F34434">
                            No
                        </a>
                    </div>
                </div>
            </div>
            
        </form>
    </div>
</div>
{% endblock %}

final_exam/addressbook/templates/addressbook/contact_detail.html
{% extends 'layouts/base.html' %} 
{% load static %} 

{% block content %}
<div class="container-login100">
    <div class="wrap-login100">
        <div class="login100-form-title" style="background-image: url({% static 'images/header.jpg' %});">
            <span class="login100-form-title-1">
                Contact
            </span>
            <div class="row">
                <div class="col-md-12">
                    <a href="{% url 'index' %}" class="btn btn-info">Back <i class="fa fa-arrow-left"></i></a>
                </div>
            </div>
        </div>

        <form class="login100-form validate-form" method="POST">
            {% csrf_token %}

            <div class="wrap-input100 validate-input m-b-26" data-validate="First Name is required">
                <span class="label-input100">First Name</span>
                <input class="input100" type="text" name="first_name" maxlength="200" required id="id_first_name" value="{% if form.first_name.value %} {{ form.first_name.value }} {% endif %}">
                <span class="focus-input100"></span>
            </div>

            {{ form.first_name.errors }}

            <div class="wrap-input100 validate-input m-b-26" data-validate="Last Name is required">
                <span class="label-input100">Last Name</span>
                <input class="input100" type="text" name="last_name" maxlength="200" required id="id_last_name" value="{% if form.last_name.value %} {{ form.last_name.value }} {% endif %}">
                <span class="focus-input100"></span>
            </div>

            {{ form.last_name.errors }}

            <div class="wrap-input100 validate-input m-b-26" data-validate="Contact Number is required">
                <span class="label-input100">Contact Number (09xxxxxxxxx/+639xxxxxxxxx)</span>
                <input class="input100" type="text" name="contact_number" required id="id_contact_number" value="{% if form.contact_number.value %} {{ form.contact_number.value }} {% endif %}">
                <span class="focus-input100"></span>
            </div>

            {{ form.contact_number.errors }}

            <div class="wrap-input100 validate-input m-b-26" data-validate="Address is required">
                <span class="label-input100">Address</span>
                <input class="input100" type="text" name="address" required id="id_address" value="{% if form.address.value %} {{ form.address.value }} {% endif %}">
                <span class="focus-input100"></span>
            </div>

            {{ form.address.errors }}

            <div class="container-login100-form-btn">
                <button class="login100-form-btn" type="submit">
                    Save
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

final_exam/addressbook/templates/addressbook/contact_form.html
{% extends 'layouts/base.html' %} 
{% load static %} 

{% block content %}
<div class="container-login100">
    <div class="wrap-login100">
        <div class="login100-form-title" style="background-image: url({% static 'images/header.jpg' %});">
            <span class="login100-form-title-1">
                Contact
            </span>
            <div class="row">
                <div class="col-md-12">
                    <a href="{% url 'index' %}" class="btn btn-info">Back <i class="fa fa-arrow-left"></i></a>
                </div>
            </div>
        </div>

        <form class="login100-form validate-form" method="POST">
            {% csrf_token %}

            <div class="wrap-input100 validate-input m-b-26" data-validate="First Name is required">
                <span class="label-input100">First Name</span>
                <input class="input100" type="text" name="first_name" maxlength="200" required id="id_first_name" value="{% if form.first_name.value %} {{ form.first_name.value }} {% endif %}">
                <span class="focus-input100"></span>
            </div>

            {{ form.first_name.errors }}

            <div class="wrap-input100 validate-input m-b-26" data-validate="Last Name is required">
                <span class="label-input100">Last Name</span>
                <input class="input100" type="text" name="last_name" maxlength="200" required id="id_last_name" value="{% if form.last_name.value %} {{ form.last_name.value }} {% endif %}">
                <span class="focus-input100"></span>
            </div>

            {{ form.last_name.errors }}

            <div class="wrap-input100 validate-input m-b-26" data-validate="Contact Number is required">
                <span class="label-input100">Contact Number (09xxxxxxxxx/+639xxxxxxxxx)</span>
                <input class="input100" type="text" name="contact_number" required id="id_contact_number" value="{% if form.contact_number.value %} {{ form.contact_number.value }} {% endif %}">
                <span class="focus-input100"></span>
            </div>

            {{ form.contact_number.errors }}

            <div class="wrap-input100 validate-input m-b-26" data-validate="Address is required">
                <span class="label-input100">Address</span>
                <input class="input100" type="text" name="address" required id="id_address" value="{% if form.address.value %} {{ form.address.value }} {% endif %}">
                <span class="focus-input100"></span>
            </div>

            {{ form.address.errors }}

            <div class="container-login100-form-btn">
                <button class="login100-form-btn" type="submit">
                    Save
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

final_exam/addressbook/templates/addressbook/contact_import.html
{% extends 'layouts/base.html' %} 
{% load static %} 

{% block content %}
<div class="container-login100">
    <div class="wrap-login100">
        <div class="login100-form-title" style="background-image: url({% static 'images/header.jpg' %});">
            <span class="login100-form-title-1">
                Import Contacts
            </span>
            <div class="row">
                <div class="col-md-12">
                    <a href="{% url 'index' %}" class="btn btn-info">Back <i class="fa fa-arrow-left"></i></a>
                </div>
            </div>
        </div>
        
        <div class="row mt-3">
            <div class="col-md 12 text-center">
                {% if messages %}
                <ul class="messages text-info">
                    {% for message in messages %}
                    <li{% if message.error %} class="{{ message.error }} text-info" {% endif %}>{{ message }}</li>
                        {% endfor %}
                </ul>
                {% endif %}
            </div>
        </div>

        <form class="login100-form validate-form" method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="row">
                <div class="col-md-12">
                    <p>Upload your contacts</p>
                </div>
            </div>
            <div class="wrap-input100 validate-input m-b-26 mt-3" data-validate="CSV File is required">
                <input class="input100" type="file" name="file_contacts" required id="id_csv">
                <span class="focus-input100"></span>
            </div>
            
            <div class="container-login100-form-btn">
                <button class="login100-form-btn mr-3" type="submit">
                    Upload
                </button>
            </div>
            
        </form>
    </div>
</div>
{% endblock %}

final_exam/addressbook/templates/addressbook/home.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
<div class="container-login100">
    <div class="wrap-login100" style="width: 900px;">
        <div class="login100-form-title" style="background-image: url({% static 'images/header.jpg' %});">
            <span class="login100-form-title-1">
                Your Address Book
            </span>
            <div class="row mt-3">
                <div class="col-md-12 text-center">
                    <a href="{% url 'logout' %}" class="text-light">Logout</a>
                </div>
            </div>
        </div>

        <div class="container">
            
        
            <div class="row mt-3">
                <div class="col-md-12 text-right">
                    <a href="{% url 'add_contact' %}" class="btn btn-primary">Add Contact <i class="fa fa-plus"></i></a>
                    <a href="{% url 'import_contact' %}" class="btn btn-info">Import CSV <i class="fa fa-upload"></i></a>
                    <a href="{% url 'export_contact' %}" class="btn btn-warning">Export CSV <i class="fa fa-download"></i></a>
                </div>
            </div>
        
            <div class="row mt-3">
                <div class="col-md-12 text-center">
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <th class="text-center">First Name</th>
                            <th class="text-center">Last Name</th>
                            <th class="text-center">Contact Number</th>
                            <th class="text-center">Address</th>
                            <th class="text-center">Action</th>

                            {% for ct in contact_list %}
                            <tr>
                                <td>{{ ct.first_name }}</td>
                                <td>{{ ct.last_name }}</td>
                                <td>{{ ct.contact_number }}</td>
                                <td>{{ ct.address }}</td>
                                <td>
                                    <a href="{% url 'edit_contact' contact_id=ct.id %}" class="btn btn-round btn-success"><i class="fa fa-edit"></i></a>
                                    <a href="{% url 'delete_contact' contact_id=ct.id %}" class="btn btn-round btn-danger"><i class="fa fa-trash"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>

            <div class="row mt-3 mb-5">
                <div class="col-md-12 text-center">
                    <ul class="pagination">
                        <li class="page-item">
                            {% if page_obj.has_previous %}
                            <a href="?page={{ page_obj.previous_page_number }}" class="page-link">&lt;</a>
                            {% endif %}
                        </li>
                        <li class="active" class="page-item">
                            <a class="page-link">{{ page_obj.number }}</a>
                        </li>
                        <li class="page-item">
                            {% if contact_list.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}" class="page-link">&gt;</a>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        
        
    </div>
</div>
{% endblock %}